const {chromium}=require('playwright');const fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe',headless:true});const output=[];
for(const width of [1440,820,390,430]){const p=await b.newPage({viewport:{width,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await p.goto('http://localhost:5173/');
const click=async n=>p.getByRole('button',{name:n,exact:true}).filter({visible:true}).first().click();
const check=async screen=>{await p.addScriptTag({path:'.reference/blind-accessibility/node_modules/axe-core/axe.min.js'});const axe=await p.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','best-practice']}}));const tree=await (await p.context().newCDPSession(p)).send('Accessibility.getFullAXTree');fs.writeFileSync(`.reference/blind-accessibility/${process.argv[2]||'after'}-${screen}-${width}-tree.json`,JSON.stringify(tree));const dom=await p.evaluate(()=>({main:document.querySelectorAll('main').length,h1:document.querySelectorAll('h1').length,focus:document.activeElement.tagName,overflow:document.documentElement.scrollWidth>innerWidth}));output.push({width,screen,...dom,violations:axe.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})),errors:[...errors]});if(width===390||width===1440)await p.screenshot({path:`.reference/blind-accessibility/${process.argv[2]||'after'}-${screen}-${width}.png`});};
await check('welcome');await click('Continuar');await check('accessibility');await click('Guardar y continuar');await check('home');
for(const [name,screen] of [['Mis listas','lists'],['Buscar producto','search'],['Mi ruta','route'],['Presupuesto','budget'],['Mi carrito','cart'],['Solicitar asistencia','help']]){if(width<769)await click('Abrir menú');await click(name);await check(screen);if(screen==='lists'){await click('Nueva lista');await check('new-list');await click('Mis listas')}}await p.close();}
fs.writeFileSync(`.reference/blind-accessibility/${process.argv[2]||'after'}.json`,JSON.stringify(output,null,2));console.log(output.map(x=>({width:x.width,screen:x.screen,violations:x.violations.map(v=>v.id),focus:x.focus,overflow:x.overflow})));await b.close()})().catch(e=>{console.error(e);process.exit(1)});

