const fs=require('fs');function edit(p,f){fs.writeFileSync(p,f(fs.readFileSync(p,'utf8')))}
for(const file of ['Welcome','Accessibility','Home','Lists','NewList','Search','Route','Budget','Cart','Assistance'])edit(`src/screens/${file}.jsx`,s=>s.replaceAll('id="main-content"','id="contenido-principal"'));
edit('src/components/AccessibilityProvider.jsx',s=>s.replaceAll('main-content','contenido-principal'));
for(const [file,id,prefix] of [['Accessibility','ac-title','Configuración de accesibilidad. '],['Home','home-title','Inicio. '],['Route','rt-title','Mi ruta. '],['Assistance','as-title','Solicitar asistencia. ']])edit(`src/screens/${file}.jsx`,s=>s.replace(`<h1 id="${id}">`,`<h1 id="${id}"><span className="a11y-sr-only">${prefix}</span>`));
edit('src/screens/Search.jsx',s=>s.replace('<input ref={inputRef} type="search" aria-label="Buscar producto"','<label className="a11y-sr-only" htmlFor="sp-search-input">Buscar producto</label><input id="sp-search-input" ref={inputRef} type="search"').replace('<select aria-label="Más categorías"','<label className="a11y-sr-only" htmlFor="sp-more-categories">Más categorías</label><select id="sp-more-categories"').replace('alt={`${product.name}, ${product.brand}`}','alt=""').replace('aria-label={`Seleccionar ${product.name} ${product.brand}`}','aria-label={`Seleccionar ${product.name} ${product.unit} ${product.brand}`}'));
edit('src/screens/NewList.jsx',s=>s.replace('<input type="number" min="1" max="99" step="1" aria-label={`Cantidad de ${product.name}`}','<label className="a11y-sr-only" htmlFor={`nl-quantity-${product.id}`}>Cantidad de {product.name}</label><input id={`nl-quantity-${product.id}`} type="number" min="1" max="99" step="1"').replace('id="nl-name" aria-describedby="nl-status"','id="nl-name" aria-describedby="nl-status" aria-invalid={!name.trim() && message.startsWith(\'Escribe el nombre\')}').replace('id="nl-search" type="search"','id="nl-search" aria-describedby="nl-status" type="search"'));
edit('src/screens/Accessibility.jsx',s=>s.replace('alt={`${product.name}, ${product.brand}`}','alt=""'));
edit('src/screens/Route.jsx',s=>{
 s="import { useAnnounce } from '../components/accessibilityContext.js'\n"+s;
 s=s.replace('  const [undo,','  const announce = useAnnounce()\n  const [undo,');
 s=s.replace('onFound(product.id, requiredQuantity(list, product.id))','onFound(product.id, requiredQuantity(list, product.id))\n    const next = products.slice(position).find(item => !progress.foundIds.includes(item.id))\n    announce(`${product.name} marcado como encontrado. ${next ? `Siguiente producto del recorrido: ${next.name}, pasillo ${next.aisle}.` : \'No quedan paradas posteriores; puedes revisar los pendientes o ir a caja.\'}`)');
 const old="<h3>Productos pendientes</h3><ul>{pending.map(item => <li key={item.id}>{item.name}, {item.unit}. Pasillo {item.aisle}, {item.shelf}. {!item.available && 'Agotado.'}</li>)}</ul>";
 const next="<p>{pending.length} productos pendientes. Después: {upcoming.length ? upcoming.join(', ') : 'Caja'}.</p><h3>Recorrido completo</h3><ol>{products.map((item, step) => <li key={item.id} aria-current={step + 1 === position ? 'step' : undefined}>{item.name}, {item.unit}. Zona: {item.category}. Pasillo {item.aisle}, {item.shelf}. {progress.foundIds.includes(item.id) ? 'Encontrado.' : 'Pendiente.'} {!item.available && 'Agotado.'}</li>)}<li aria-current={!product ? 'step' : undefined}>Caja. Revisa tu carrito y completa la compra.</li></ol>";
 if(!s.includes(old))throw Error('Route text changed');s=s.replace(old,next);
 s=s.replace('className="rt-found-note" role="status"','className="rt-found-note"');return s;
});
