const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('fs');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe',headless:true});const report=[];
for(const width of [320,390,430]){const p=await browser.newPage({viewport:{width,height:1000}});p.setDefaultTimeout(6000);const errors=[];p.on('pageerror',e=>errors.push(e.message));const keys=[];
async function reach(locator){await locator.waitFor();for(let i=0;i<500;i++){if(await locator.evaluate(el=>el===document.activeElement))return;await p.keyboard.press('Tab');keys.push('Tab')}throw Error('No keyboard access: '+await locator.innerText())}
const btn=n=>p.getByRole('button',{name:n,exact:true}).filter({visible:true}).first();const press=async(n,key='Enter')=>{await reach(btn(n));await p.keyboard.press(key);keys.push(key)};
async function view(name){await p.waitForFunction(()=>document.activeElement.tagName==='H1');assert.equal(await p.locator('main').count(),1);assert.ok((await p.title()).includes(name));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
async function nav(name){if(width<769)await press('Abrir menú');await press(name);await view(name)}
async function modalCheck(selector){await p.locator(selector+'[open]').waitFor();assert.ok(await p.evaluate(()=>!!document.activeElement.closest('dialog[open]')));for(let i=0;i<12;i++){await p.keyboard.press(i%2?'Shift+Tab':'Tab');keys.push(i%2?'Shift+Tab':'Tab');assert.ok(await p.evaluate(()=>!!document.activeElement.closest('dialog[open]')))}}
await p.goto('http://localhost:5173/');await view('Bienvenida');await press('Continuar');await view('Configuración');
for(const name of ['Texto más grande','Alto contraste','Botones simplificados']){const field=p.getByRole('checkbox',{name,exact:true});await reach(field);if(await field.isChecked()){await p.keyboard.press('Space');keys.push('Space')}}
assert.equal(await p.getByRole('checkbox',{name:'Comandos de voz',exact:true}).isChecked(),false);await press('Guardar y continuar');await view('Inicio');await nav('Mis listas');
await press('Abrir Compra semanal');await p.waitForFunction(()=>document.activeElement.classList.contains('lists-detail-panel'));assert.ok(await p.locator('.lists-detail-panel').evaluate(e=>e===document.activeElement));await press('Editar Compra semanal');await p.waitForFunction(()=>document.activeElement.id==='lists-edit-name');await p.keyboard.press('Control+A');await p.keyboard.type('Compra semanal revisada');await press('Guardar');await press('Listo');await press('Eliminar Productos de limpieza');assert.ok(await p.locator('.lists-delete-confirm').evaluate(e=>e.contains(document.activeElement)));await p.keyboard.press('Escape');keys.push('Escape');assert.equal(await p.locator('.lists-delete-confirm').count(),0);
await press('Nueva lista');await view('Nueva lista');await press('Guardar lista');assert.equal(await p.evaluate(()=>document.activeElement.id),'nl-name');await p.keyboard.type('Lista de teclado');await reach(p.getByLabel('Buscar producto',{exact:true}));await p.keyboard.type('arroz');await press('Agregar Arroz');await press('Aumentar cantidad de Arroz');await press('Guardar lista');await view('Mis listas');await press('Abrir Lista de teclado');await press('Iniciar compra');await view('Mi ruta');
await nav('Buscar producto');await reach(p.getByRole('searchbox',{name:'Buscar producto',exact:true}));await p.keyboard.type('leche');await p.keyboard.press('Enter');keys.push('Enter');assert.equal(await p.evaluate(()=>document.activeElement.tagName),'H2');await press('Agregar al carrito: Leche entera LALA');await press('Ver ubicación de Leche entera LALA');assert.equal(await btn('Ver ubicación de Leche entera LALA').getAttribute('aria-expanded'),'true');await press('Cerrar detalle');assert.ok(await btn('Ver ubicación de Leche entera LALA').evaluate(e=>e===document.activeElement));
await press('Buscar por códigoBusca un producto con su código').catch(async()=>{await reach(p.locator('.sp-code'));await p.keyboard.press('Enter')});await modalCheck('.barcode-scanner');await reach(p.getByLabel('Código de barras',{exact:true}));await p.keyboard.type('9999999999999');await press('Buscar código');await p.getByRole('heading',{name:'Producto no encontrado',exact:true}).waitFor();await p.keyboard.press('Escape');assert.ok(await p.locator('.sp-code').evaluate(e=>e===document.activeElement));
await nav('Mi ruta');assert.match(await p.getByRole('region',{name:'Recorrido en texto'}).innerText(),/Arroz.*Pasillo/s);await press('Producto encontrado');await press('Siguiente');await nav('Presupuesto');await reach(p.locator('.bd-budget'));await p.keyboard.press('Enter');await p.waitForFunction(()=>document.activeElement.id==='bd-budget-input');await p.keyboard.press('Control+A');await p.keyboard.type('20');await press('Guardar presupuesto');assert.ok(await p.locator('.bd-budget').evaluate(e=>e===document.activeElement));
await nav('Mi carrito');await press('Agregar una unidad de Leche entera LALA');await press('Quitar una unidad de Leche entera LALA');await press('Finalizar compra');await modalCheck('.ct-dialog');await press('Confirmar y continuar a caja');assert.equal(await p.evaluate(()=>document.activeElement.id),'ct-dialog-title');await p.keyboard.press('Escape');assert.ok(await btn('Finalizar compra').evaluate(e=>e===document.activeElement));await press('Eliminar Leche entera LALA del carrito');assert.notEqual(await p.evaluate(()=>document.activeElement.tagName),'BODY');
await nav('Solicitar asistencia');await reach(p.locator('.as-option').nth(2));await p.keyboard.press('Space');keys.push('Space');assert.equal(await p.locator('.as-option').nth(2).getAttribute('aria-pressed'),'true');await press('Mostrar mensaje en pantalla');await modalCheck('.as-dialog');await press('Confirmar solicitud');assert.ok(await p.locator('.as-confirmation').evaluate(e=>e===document.activeElement));await p.keyboard.press('Escape');assert.ok(await btn('Mostrar mensaje en pantalla').evaluate(e=>e===document.activeElement));
if(width<769){await press('Abrir menú');assert.equal(await btn('Cerrar menú').getAttribute('aria-expanded'),'true');await p.keyboard.press('Escape');assert.ok(await btn('Abrir menú').evaluate(e=>e===document.activeElement))}
const cdp=await p.context().newCDPSession(p);const tree=await cdp.send('Accessibility.getFullAXTree');fs.writeFileSync(`.reference/final-accessibility/keyboard-${width}-tree.json`,JSON.stringify(tree));assert.deepEqual(errors,[]);report.push({width,keyboardOnly:true,keys:[...new Set(keys)],errors});await p.close()}
fs.writeFileSync('.reference/final-accessibility/keyboard-report.json',JSON.stringify(report,null,2));console.log(report);await browser.close()})().catch(e=>{console.error(e);process.exit(1)});



